[project]
name = "new-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clingo>=5.8.0",
    "clorm>=1.6.1",
    "fastapi[standard]>=0.124.4",
    "uvicorn>=0.38.0",
]
